services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile.${NODE_ENV}
    volumes:
      # it avoids mounting the workspace root
      # because it may cause OS specific node_modules folder
      # or build folder(.svelte-kit) to be mounted.
      # they conflict with the temporary results from docker space.
      # this is why many mono repos utilize ./src folder
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${EXPOSE_PORT}:5173"
    command: yarn dev --host
