name = "sv-app"
account_id = "8cccd0b31e0328a6e9a3e263f8dfa253"

pages_build_output_dir = ".svelte-kit/cloudflare"


kv_namespaces = [
    { binding = "COUNTER", id = "868d3cfef04049d5856c661e2e10605d" }
]

compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-01-03"

workers_dev = true